In [1]:
import numpy as np
import scipy.stats as sps
import pandas as pd

In [51]:
def bonus_malus(premium, starting_level=1, final_level=6, discount=1, penalty=2, distribution = 'poisson'):
    premium = pd.Series(premium)
    m, n = starting_level, final_level
    sinx = np.arange(0, 3)
    levels = pd.Series(np.arange(m, n+1), dtype='int64')
    claims = pd.Series(np.arange(0,(final_level/penalty)+1), dtype='int64')
    claim_free = pd.Series(levels.shift(discount).fillna(starting_level), dtype='int64')
    claim_one = pd.Series(levels.shift(-penalty).fillna(final_level), dtype='int64')
    claim_two = pd.Series(levels.shift(-penalty*2).fillna(final_level), dtype='int64')
    claim_three = pd.Series(levels.shift(-penalty*3).fillna(final_level), dtype='int64')
    print(f'Transition Rules for the scale -{discount}/+{penalty}')
    print('='*40)
    print('   Levels|   Claims Incurred')
    df = pd.DataFrame({'Levels':levels, 'Claim-free':claim_free,
                       f'{claims[1]}:claim':claim_one, f'{claims[2]}:claim':claim_two,
                      f'+{claims[2]}:claim':claim_three})
    print(df)
    df1 = df.iloc[:,1:-1].values-1   ## posiciones index matrix

    mu = float(input('Insert mu parameter for Poisson: \n'))
    p0 = sps.poisson.pmf(sinx, mu)
    mat1 = np.matrix(np.zeros((final_level)**2).reshape((final_level),(final_level)))
    mat1[0,[df1[0,0]]], mat1[0, [df1[0,1]]] = p0[0], p0[1]
    mat1[1,[df1[1,0]]], mat1[1, [df1[1,1]]] = p0[0], p0[1]
    mat1[2,[df1[2,0]]], mat1[2, [df1[2,1]]]= p0[0], p0[1]
    mat1[3,[df1[3,0]]], mat1[3, [df1[3,1]]] = p0[0], p0[1]
    mat1[4,[df1[4,0]]], mat1[4, [df1[4,1]]] = p0[0], p0[1]
    mat1[5,[df1[5,0]]], mat1[5, [df1[5,1]]]  = p0[0], p0[1]
    mat1[0,5], mat1[1, 5] = 1-p0[0]-p0[1], 1-p0[0]-p0[1]
    mat1[2,5], mat1[3,5] = 1-p0[0]-p0[1], 1-p0[0]
    mat1[4, 5], mat1[5,5]= 1-p0[0], 1-p0[0]
    
    def formula_rolski():
        et = np.repeat(1, 6)
        E = np.ones((6, 6))
        mat = np.eye(6)-ma+E
        inverse = np.linalg.inv(mat)
        stat_dist = np.matmul(et, inverse)
        
        return  stat_dist
    print('='*40)
    print('Stationary Distribution (Rolski Formula)')
    print(formula_rolski())   

In [52]:
bonus_malus(3)

Transition Rules for the scale -1/+2
   Levels|   Claims Incurred
   Levels  Claim-free  1:claim  2:claim  +2:claim
0       1           1        3        5         6
1       2           1        4        6         6
2       3           2        5        6         6
3       4           3        6        6         6
4       5           4        6        6         6
5       6           5        6        6         6
Insert mu parameter for Poisson: 
.04
Stationary Distribution (Rolski Formula)
[0.91526921 0.03747454 0.03912614 0.00423589 0.00303209 0.00097959]


In [9]:
et = np.repeat(1, 6)
E = np.ones((6, 6))
mat = np.eye(6)-ma+E
mat

matrix([[1.03921056, 1.        , 0.96156842, 1.        , 0.99923137,
         0.99922102],
        [0.03921056, 2.        , 1.        , 0.96156842, 1.        ,
         0.99922102],
        [1.        , 0.03921056, 2.        , 1.        , 0.96156842,
         0.99922102],
        [1.        , 1.        , 0.03921056, 2.        , 1.        ,
         0.96078944],
        [1.        , 1.        , 1.        , 0.03921056, 2.        ,
         0.96078944],
        [1.        , 1.        , 1.        , 1.        , 0.03921056,
         1.96078944]])

In [31]:
np.matmul(et,np.linalg.inv(mat))

matrix([[0.91527262, 0.03747502, 0.03912644, 0.00423435, 0.0030302 ,
         0.00097862]])

In [28]:
ma =bonus_malus(2)

Transition Rules for the scale -1/+2
   Levels|   Claims Incurred
   Levels  Claim-free  1:claim  2:claim  +2:claim
0       1           1        3        5         6
1       2           1        4        6         6
2       3           2        5        6         6
3       4           3        6        6         6
4       5           4        6        6         6
5       6           5        6        6         6
Insert mu parameter for Poisson: 
.04


In [76]:
ok = sps.poisson.pmf([0, 1, 2], .04)
ok[0]

0.9607894391523232

In [70]:
mat = np.zeros(36)

In [71]:
mat = mat.reshape(6,6)
mat[0,2] = 1

In [74]:
mat[0]

array([0., 0., 1., 0., 0., 0.])

In [83]:
q  = list(bon.iloc[0,1:].values)[:-1]
q = [x-1 for x in q]
q

[0, 2, 4]

In [61]:
it = bonus_malus(2, starting_level=1, final_level=6, discount=1, penalty=2).iloc[:,1:-1].values-1

Transition Rules for the scale -1/+2
   Levels|   Claims Incurred


In [62]:
it[0]

array([[0, 2, 4],
       [0, 3, 5],
       [1, 4, 5],
       [2, 5, 5],
       [3, 5, 5],
       [4, 5, 5]], dtype=int64)

In [20]:
q0 =  pd.Series(np.zeros(6)) 
q0[1] = 1
q0

0    0.0
1    1.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [21]:
q1 =  pd.Series(np.zeros(6)) 
q1[3] = 1
q1

0    0.0
1    0.0
2    0.0
3    1.0
4    0.0
5    0.0
dtype: float64

In [27]:
pd.concat([q0, q1], ignore_index=True).values.reshape(2,6)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [46]:
mat1 = np.matrix(np.zeros(36).reshape(6,6))
mat1[0,0], mat1[0, 2] = 1, 1
mat1

matrix([[1., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [38]:
q

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

In [10]:
def premiums_poisgamma(lambdas, a, b, delta):
    equi = lambdas*a/b
    expected = equi*(1+delta)
    fact = ((a+a**2)/b**2)*lambdas
    varianza = equi+delta*fact
    des = equi+np.sqrt(fact)*delta
    df = pd.Series({'Equivalencia':equi, 'Valor esperado':expected, 
                      'Varianza':varianza, 'Desviacion':des})
    return df

def premiums_nbinexp(a, b, beta, delta):
    equi = a*b*1/beta
    expected = equi*(1+delta)
    fact = (2*a*b+a*b**2)/beta**2
    varianza = equi+delta*fact
    des = equi+delta*np.sqrt(fact)
    df = pd.Series({'Equivalencia':equi, 'Valor esperado':expected, 
                      'Varianza':varianza, 'Desviacion':des})
    return df

In [14]:
resultado = premiums_poisgamma(lambdas=.95, a=1.699511, b=.003161881, delta=.02)
print(resultado.round(2))

Equivalencia       510.62
Valor esperado     520.84
Varianza          9229.72
Desviacion         523.83
dtype: float64


In [15]:
resultado2 = premiums_nbinexp(a=.9140635, b=.1407634, beta=.00059829, delta = .02)
print(resultado2.round(2))

Equivalencia        215.06
Valor esperado      219.36
Varianza          15605.15
Desviacion          232.60
dtype: float64
